export type ModeloAta = { tema: string; descricao: string };

export const MODELOS_ATA: ModeloAta[] = [
  {
    tema: "TEMPO LOGADO",
    descricao:
      "O presente documento tem por objetivo registrar e formalizar o alinhamento realizado junto à equipe acerca da obrigatoriedade do cumprimento integral da jornada diária de trabalho, estabelecida em 6 horas e 20 minutos (06:20:00) diárias.\nO não cumprimento desta jornada ao término de cada dia poderá acarretar, futuramente, a aplicação de Feedback Formal e, em caso de reincidência, o escalonamento progressivo de medidas disciplinares, a critério da supervisão.\nReconhece-se que situações imprevistas e casos atípicos podem ocorrer no decorrer da jornada. Nesses cenários, é obrigatória a comunicação imediata com a supervisão, a fim de que seja registrada a devida justificativa. Ressalta-se que toda e qualquer ocorrência fora do padrão estabelecido deve ser reportada no mesmo dia em que ocorreu, sem exceção.\nO presente comunicado foi devidamente apresentado e alinhado com a equipe, ficando todos os colaboradores cientes das disposições aqui registradas.",
  },
  {
    tema: "ADERÊNCIA",
    descricao:
      "O presente documento tem por objetivo registrar e formalizar o alinhamento realizado junto à equipe acerca da obrigatoriedade do login pontual na plataforma Five9, conforme os horários estabelecidos pela escala de trabalho. Operadores do turno padrão devem realizar o login às 14:00, enquanto operadores do turno alternativo devem realizá-lo às 13:00, cumprindo a escala até às 20:20 ou 19:20, respectivamente.\nAtrasos recorrentes no login à plataforma ocasionam filas desnecessárias e impactam negativamente a operação como um todo. Devido à gravidade desse impacto, o não cumprimento do horário de login acordado, respeitada uma margem mínima de tolerância, poderá acarretar a aplicação de Feedback Formal e, em caso de reincidência, o escalonamento progressivo de medidas disciplinares.\nReconhece-se que atrasos atípicos podem ocorrer, bem como atrasos recorrentes decorrentes do transporte proveniente de Além Paraíba. Nesses casos, é obrigatório que o colaborador reporte a ocorrência à supervisão no mesmo dia, a fim de que o registro seja devidamente alinhado e o colaborador não seja penalizado futuramente sem a devida justificativa.\nO presente comunicado foi devidamente apresentado e alinhado com a equipe, ficando todos os colaboradores cientes das disposições aqui registradas.",
  },
  {
    tema: "PAUSAS NÃO AUTORIZADAS",
    descricao:
      "O presente documento tem por objetivo registrar e formalizar o alinhamento realizado junto à equipe acerca do uso correto das pausas disponíveis na plataforma. Embora os operadores possuam acesso livre ao sistema para o registro de pausas, apenas três modalidades são oficialmente autorizadas: Pausa 10, Pausa 20 e Pausa Particular.\nO registro de qualquer pausa fora das modalidades mencionadas, independentemente do tempo de duração, poderá sujeitar o colaborador ao registro de Feedback Formal e, em caso de reincidência, ao escalonamento progressivo de medidas disciplinares. É importante destacar que todos os registros são monitorados diariamente, com controle detalhado do tempo e da categoria de cada pausa lançada na plataforma.\nEm situações de demandas internas ou necessidades que exijam o uso de pausas não previstas, o colaborador deve, obrigatoriamente, solicitar autorização prévia à supervisão antes de realizar o registro, a fim de que a ocorrência seja devidamente justificada e não impacte negativamente o KPI mensal do operador.\nO presente comunicado foi devidamente apresentado e alinhado com a equipe, ficando todos os colaboradores cientes das disposições aqui registradas.",
  },
  {
    tema: "ESTOURO DO NR17",
    descricao:
      "O presente documento tem por objetivo registrar e formalizar o alinhamento realizado junto à equipe acerca do cumprimento do indicador de NR17 e do uso adequado das pausas ao longo da jornada diária de trabalho.\nDentro da jornada diária de 06 horas e 20 minutos, o operador tem permissão para registrar um total de até 40 minutos de pausas, considerando a soma da Pausa 10 e da Pausa 20, não sendo a Pausa Particular contabilizada nesse limite. O percentual de NR17 não pode ultrapassar 10,5% ao dia, sendo esse o limite máximo permitido para cada operador. Qualquer registro que exceda esse percentual será identificado no relatório extraído diariamente ao término da jornada e poderá resultar no registro de Feedback Formal e, em caso de reincidência, no escalonamento progressivo de medidas disciplinares.\nReconhece-se que erros e situações atípicas podem ocorrer. Nesses casos, é obrigatório que o colaborador reporte a ocorrência à supervisão no mesmo dia, antes da extração do relatório sempre que possível, a fim de que seja registrado o devido alinhamento, aviso prévio e justificativa, resguardando o colaborador de eventuais penalizações.\nO presente comunicado foi devidamente apresentado e alinhado com a equipe, ficando todos os colaboradores cientes das disposições aqui registradas.",
  },
];
